apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: edip-replica
  labels:
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: edipnginx
        image: nginx
        ports:
          - containerPort: 80
