apiVersion: v1
kind: Pod
metadata:
  name: edip-pod
  labels:
    name: storage
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    imagePullPolicy: Always
    resources:
      limits:
        memory: "200Mi"
        cpu: "200m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: edip-storage
  volumes:
    - name: edip-storage
      persistentVolumeClaim:
        claimName: edip-pvc
