apiVersion: apps/v1
kind: Deployment
metadata:
  name: edip-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache-container
        image: k8s.gcr.io/hpa-example
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
          requests:
            memory: "250Mi"
            cpu: "80m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: edip-php-svc
spec:
  type: NodePort
  selector:
    app: php-apache
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31311
    protocol: TCP
