apiVersion: v1
kind: Pod
metadata:
  name: edip-secret
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: EDIP_USERNAME
        valueFrom:
          secretKeyRef:
            name: edipsecret
            key: username
      - name: EDIP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: edipsecret
            key: password
  restartPolicy: Never