apiVersion: apps/v1
kind: Deployment
metadata:
  name: edip-deploy
  labels:
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: edipnginx
        image: nginx:1.19
        ports:
        - containerPort: 80