apiVersion: v1
kind: Service
metadata:
  name: edip-svc
  namespace: demo
  labels:
    app: web-flask
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 5000 
    nodePort: 31310 
  selector:
    env: front-end