apiVersion: apps/v1
kind: Deployment
metadata:
  name: edip-web
  namespace: demo
  labels:
    app: web-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-flask
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-flask
        env: front-end
        version: v1
    spec:
      containers:
      - name: edip-flask
        image: clarusway/cw_web_flask1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000